[[section-introduction-and-goals]]
==	Einführung und Ziele




=== Aufgabenstellung

===== Fachlich

Survey System um beliebiege Umfragen erstellen zu können. 
Die Umfragen sollen anonym sein. Das heisst die Personenbezogene Daten dürfen nicht gespeichert werden. 
Es sollen keine Daten über Herkunft des Geräts des Anwenders, IP Adresse oder ähnliches nachvollzogen werden können.
Das Projekt soll als OpenSource Projekt betrieben und angeboten werden.

===== Technisch

Erstellung eines System, das eine Web basierte Anwendung beinhaltet. Die Web Anwendung soll mit allen gängigen Geräte
kompatibel sein. Das System soll die Möglichkeit anbieten, Offline betrieben zu werden. 

=== Qualitätsziele

Erfüllung der Datensschutz relevante Regularien.

=== Stakeholder





[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| Architekt, Entwickler | Andrei Sava | Anforderungen stellen und Weiterentwicklung
| Architekt, Entwickler | Constantin Krüger | Anforderungen stellen und Weiterentwicklung
| Comunity | Comunity | Anforderungen stellen und Weiterentwicklung
|===
